# -*- coding: utf-8 -*-
"""Week6GetReturns

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiB2aya4Ms3n4uFvTQUqAxvdL0iXXNzP
"""

#If don't need to download from Yahoo
import numpy as np
import pandas as pd

def YahooDatareturns(YahooData):
  if 'Adj Close' not in YahooData:
    raise ValueError("YahooData don't contain 'Adj Close' column.")

  pricevec =YahooData['Adj Close'].values
  returns =pricevec[1:]/pricevec[:-1]-1
  return returns

d = {   'Open': [100, 102, 101, 103],
        'High': [105, 104, 103, 105],
        'Low': [98, 100, 99, 101],
        'Close': [101, 103, 102, 104],
        'Adj Close': [101, 103, 102, 104],
        'Volume': [1000, 1200, 900, 1100]}

index = pd.to_datetime(['2023-10-26', '2023-10-27', '2023-10-28', '2023-10-29'])
tempdata = pd.DataFrame(d, index=index)
returns = YahooDatareturns(tempdata)
print(returns)

#Draw Data from Yahoo
import yfinance as yf
import pandas as pd
import numpy as np

def YahooData2returns(YahooData):

  def get_stock_data(symbol):
    data = yf.download(symbol)
    if 'Adj Close' not in data:
      raise ValueError("YahooData don't contain 'Adj Close' column.")
    prices = data['Adj Close']
    return prices
    print(type(prices))
    pricevec = prices.values

  def get_returns(pricevec):
    n = len(pricevec)
    ratiovec = pricevec[1:n] / pricevec[:n-1]
    returns = ratiovec - 1  # assuming the return calculation is (price_t / price_t-1) - 1
    return returns

