# -*- coding: utf-8 -*-
"""Week6GetReturns

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiB2aya4Ms3n4uFvTQUqAxvdL0iXXNzP
"""

import yfinance as yf
import pandas as pd

def YahooData2returns(YahooData):

  def get_stock_data(symbol):
    data = yf.download(symbol)
    prices = data['Adj Close']
    return prices

# Example usage
  prices = get_stock_data('GS')
  print(type(prices))
  pricevec = prices.values

# Compute the returns
  n = len(pricevec)
  ratiovec = pricevec[1:n] / pricevec[:n-1]

def get_returns(pricevec):
    n = len(pricevec)
    ratiovec = pricevec[1:n] / pricevec[:n-1]
    returns = ratiovec - 1  # assuming the return calculation is (price_t / price_t-1) - 1
    return returns

# Example of using get_returns
    returns = get_returns(pricevec)
    print(returns)



